<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
    public function getByIds(array $ids)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p 
                     FROM AppBundle:Project p
                     WHERE p.id IN (:ids)'
            )
            ->setParameter('ids', $ids)
            ->getResult();
    }
}
